# Generated by Django 4.1.7 on 2023-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_adicionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(max_length=15, verbose_name='Nº da Conta')),
                ('agencia', models.CharField(max_length=15, verbose_name='Agência')),
            ],
            options={
                'verbose_name': 'Dados de Banco',
                'verbose_name_plural': 'Dados Bancários',
            },
        ),
    ]
