# Generated by Django 4.1.7 on 2023-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_adicionais', '0002_dadosbanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbanco',
            name='agencia',
            field=models.CharField(max_length=5, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='dadosbanco',
            name='conta',
            field=models.CharField(max_length=9, verbose_name='Nº da Conta'),
        ),
    ]
