# Generated by Django 4.1.3 on 2023-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='parentesco',
            field=models.CharField(choices=[('1', 'Esposa(o)'), ('2', 'Filho(a)'), ('3', 'Neto(a)'), ('4', 'Sobrinho(a)'), ('5', 'Mãe/Pai'), ('6', 'Avó/Avô'), ('7', 'Tio(a)'), ('8', 'Outro')], default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
