# Generated by Django 4.1.3 on 2023-02-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_pessoa_dados_educacionais_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadoseducacao',
            options={'verbose_name': 'Dados de Educação', 'verbose_name_plural': 'Dados Educacionais'},
        ),
    ]
