# Generated by Django 4.1.3 on 2023-02-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_dadoseducacao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiencia', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Possui Deficiência?')),
                ('tipo_deficiencia', models.CharField(blank=True, choices=[('1', 'Física'), ('2', 'Auditiva'), ('3', 'Visual'), ('4', 'Mental/Intelectual'), ('5', 'Múltipla')], max_length=1, null=True, verbose_name='Especifique o Tipo de Deficiência')),
                ('gravidez', models.CharField(blank=True, choices=[('1', 'Gravida'), ('2', 'Não Grávida'), ('3', 'Não Se Aplica')], max_length=1, null=True, verbose_name='Gravidez')),
            ],
            options={
                'verbose_name': 'Dado de Saúde',
                'verbose_name_plural': 'Dados Saúde',
            },
        ),
        migrations.AlterModelOptions(
            name='dadoseducacao',
            options={'verbose_name': 'Dado de Educação', 'verbose_name_plural': 'Dados Educacionais'},
        ),
        migrations.AddField(
            model_name='referencia',
            name='cadastro_unico',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=1, verbose_name='Possui Cadastro Único?'),
        ),
    ]
