# Generated by Django 4.1.7 on 2023-02-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_adicionais', '0001_initial'),
        ('cadastros', '0005_dadosaude_alter_dadoseducacao_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadoSaude',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='dados_saude',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_adicionais.saude'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dados_educacionais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_adicionais.educacao'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='documentos_extras',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_adicionais.identificacao'),
        ),
        migrations.DeleteModel(
            name='DadosEducacao',
        ),
    ]
