# Generated by Django 4.1.3 on 2023-02-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_cadastro_options_alter_pessoa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='entrevistador',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='abrangencia',
            field=models.CharField(blank=True, choices=[('1', 'CRAS I'), ('2', 'CRAS II'), ('3', 'CRAS III')], max_length=1, null=True, verbose_name='Cras de Abrangência'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='entrevistador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Entrevistador'),
        ),
    ]
