# Generated by Django 4.1.3 on 2023-02-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_referencia_entrevistador_cadastro_abrangencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='data_alteracao',
            field=models.DateField(auto_now=True),
        ),
    ]
