# Generated by Django 4.1.3 on 2023-02-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_cadastro_responsavel_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(choices=[('1', 'Não Alfabetizado'), ('2', 'Fundamental Incompleto'), ('3', 'Fundamental Completo'), ('4', 'Ensino Médio Incompleto'), ('5', 'Ensino Médio Completo'), ('6', 'Ensino Superior Incompleto'), ('7', 'Ensino Superior Completo'), ('8', 'Não Informado')], max_length=1),
        ),
    ]
