# Generated by Django 4.1.3 on 2023-03-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_pessoa_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='habitacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.habitacao'),
        ),
    ]
