# Generated by Django 4.1.3 on 2023-03-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_cadastro_habitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='ponto_referencia',
        ),
        migrations.AddField(
            model_name='endereco',
            name='ruc',
            field=models.CharField(blank=True, choices=[('1', 'Nenhum'), ('2', 'Água Azul'), ('3', 'Jatobá'), ('4', 'São Joaquim'), ('5', 'Casa Nova'), ('6', 'Laranjeiras')], default='1', max_length=1, null=True, verbose_name='RUC'),
        ),
    ]
