# Generated by Django 4.1.7 on 2023-03-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_adicionais', '0001_initial'),
        ('cadastros', '0013_remove_endereco_ponto_referencia_endereco_ruc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificacao',
            options={'verbose_name': 'Identificação', 'verbose_name_plural': 'Identificações'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='contato',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dados_educacionais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_adicionais.educacao', verbose_name='Dados Educacionais'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dados_saude',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_adicionais.saude', verbose_name='Dados de Saúde'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(choices=[('1', 'Não Alfabetizado'), ('2', 'Ensino Fundamental Incompleto'), ('3', 'Ensino Fundamental Completo'), ('4', 'Ensino Médio Incompleto'), ('5', 'Ensino Médio Completo'), ('6', 'Ensino Superior Incompleto'), ('7', 'Ensino Superior Completo'), ('8', 'Não Informado')], max_length=1, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='renda',
            field=models.FloatField(blank=True, null=True, verbose_name='Renda'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('1', 'Feminino'), ('2', 'Masculino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='trabalho',
            field=models.CharField(choices=[('1', 'Não Trabalha'), ('2', 'Trabalhador Por Conta Própria'), ('3', 'Trabalhador Temporário em Área Rural'), ('4', 'Empregado Sem Carteira de Trabalho Assinada'), ('5', 'Empregado Com Carteira de Trabalho Assinada'), ('6', 'Trabalhador Doméstico Sem Carteira de Trabalho Assinada'), ('7', 'Trabalhador Não Remunerado'), ('8', 'Estagiário'), ('9', 'Aprendiz'), ('10', 'Aposentado'), ('11', 'Pensionista')], max_length=2, verbose_name='Informação de Trabalho'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='apelido',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='documentos_extras',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_adicionais.identificacao', verbose_name='Documentação Adicional'),
        ),
    ]
