# Generated by Django 4.1.7 on 2023-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_endereco_bairro_alter_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Suspenso'), ('3', 'Desligado')], default='1', max_length=1, verbose_name='Status do Cadastro'),
        ),
        migrations.AlterField(
            model_name='habitacao',
            name='equipamento_comunitario',
            field=models.ManyToManyField(to='cadastros.equipamentocomunitario', verbose_name='Equipamentos Comunitários Próximos'),
        ),
    ]
