# Generated by Django 4.1.7 on 2023-04-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_adicionais', '0002_dadosbanco'),
        ('cadastros', '0016_cadastro_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='dados_bancarios',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_adicionais.dadosbanco', verbose_name='Dados Bancários'),
        ),
    ]
