# Generated by Django 4.1.3 on 2023-05-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_alter_habitacao_pavimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='cor_raca',
            field=models.CharField(choices=[('1', 'Branca'), ('2', 'Preta'), ('3', 'Amarela'), ('4', 'Parda'), ('5', 'Indígena'), ('6', 'Não Informado')], max_length=1, verbose_name='Identificação Étnico-Racial'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='identidade_genero',
            field=models.CharField(choices=[('1', 'Cisgênero'), ('2', 'Transgênero'), ('3', 'Não Binário'), ('4', 'Não Declarado'), ('5', 'Não Informado')], max_length=1, verbose_name='Identidade de Gênero'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='situacao_civil',
            field=models.CharField(choices=[('1', 'Solteiro(a)'), ('2', 'Casado(a)'), ('3', 'Divorciado(a)'), ('4', 'Viúvo(a)'), ('5', 'Não Informado')], max_length=1, verbose_name='Situação Civil'),
        ),
    ]
