# Generated by Django 4.1.7 on 2023-03-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
        ('change_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('1', 'Adição'), ('2', 'Edição'), ('3', 'Exclusão')], max_length=1, verbose_name='Tipo da Alteração')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('id_alterado', models.IntegerField(verbose_name='ID Alterado')),
                ('tabela', models.CharField(max_length=60, verbose_name='Tabela Alterada')),
                ('indicador_alterado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicador do Dado Alterado')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnicos.tecnico', verbose_name='Responsável Pela Alteração')),
            ],
            options={
                'verbose_name': 'Alteração',
                'verbose_name_plural': 'Alterações',
            },
        ),
        migrations.AlterField(
            model_name='campochange',
            name='modificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_control.alteracao'),
        ),
        migrations.AlterField(
            model_name='tabeladadoschange',
            name='modificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_control.alteracao'),
        ),
        migrations.DeleteModel(
            name='Acao',
        ),
    ]
