# Generated by Django 4.0.6 on 2022-08-01 13:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgaos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orgao', models.CharField(max_length=200)),
                ('sigla', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150)),
                ('contato', models.CharField(blank=True, max_length=20, null=True)),
                ('cadastro_pendente', models.BooleanField(default=True)),
                ('data_registro', models.DateField(default=datetime.datetime.now)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tecnicos.orgaos', verbose_name='Órgão')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
